import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@mantine/core/styles.css";
import { env } from "@/env";
import { ColorSchemeScript, MantineProvider } from "@mantine/core";
import mongoose from "mongoose";
import { AxiomWebVitals } from "next-axiom";
import { theme } from "../lib/config/theme";
import NextAuthProvider from "./auth";
import { GoogleAnalytics } from "@next/third-parties/google";

const inter = Inter({ subsets: ["latin"] });

mongoose.connect(env.MONGODB_URI, {});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AxiomWebVitals />
      <GoogleAnalytics gaId={env.GA_TAG_ID} />
      <head>
        <ColorSchemeScript defaultColorScheme="dark" />
      </head>
      <body className={inter.className}>
        <MantineProvider theme={theme} defaultColorScheme="dark">
          <NextAuthProvider>{children}</NextAuthProvider>
        </MantineProvider>
      </body>
    </html>
  );
}
